language: java
os: linux
jdk: oraclejdk7
install: true
sudo: required

env:
  - spring'.'profiles'.'active=h2
  - spring'.'profiles'.'active=hsql
  - spring'.'profiles'.'active=derby
  - spring'.'profiles'.'active=postgresql
  - spring'.'profiles'.'active=mysql
  - spring'.'profiles'.'active=oracle

services:
  - docker

before_script:
  - mvn install -DskipTests

script:
  - mvn verify coveralls:report -DrepoToken=$repo_token -Dtest=com.github.j3t.jpa.utils.test.EntityManagerHelperImplTest -pl :jpa-utils-hibernate
  - mvn verify coveralls:report -DrepoToken=$repo_token -Dtest=com.github.j3t.jpa.utils.test.EntityManagerHelperImplTest -pl :jpa-utils-eclipselink
  - mvn verify coveralls:report -DrepoToken=$repo_token -Dtest=com.github.j3t.jpa.utils.test.EntityManagerHelperImplTest -pl :jpa-utils-openjpa
