language: java
os: linux
jdk: oraclejdk7
install: true
sudo: required

env:
  - SPRING_PROFILES_ACTIVE=h2
  - SPRING_PROFILES_ACTIVE=hsql
  - SPRING_PROFILES_ACTIVE=derby
  - SPRING_PROFILES_ACTIVE=postgresql
  - SPRING_PROFILES_ACTIVE=mysql
  - SPRING_PROFILES_ACTIVE=oracle

services:
  - docker

before_script:
  - mvn install -DskipTests

script:
  - mvn verify coveralls:report -DrepoToken=$repo_token -Dtest=com.github.j3t.jpa.utils.test.EntityManagerHelperImplTest -pl :jpa-utils-hibernate
  - mvn verify coveralls:report -DrepoToken=$repo_token -Dtest=com.github.j3t.jpa.utils.test.EntityManagerHelperImplTest -pl :jpa-utils-eclipselink
  - mvn verify coveralls:report -DrepoToken=$repo_token -Dtest=com.github.j3t.jpa.utils.test.EntityManagerHelperImplTest -pl :jpa-utils-openjpa
