language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode7.3

install: true

script: mvn verify

after_success:
  - mvn coveralls:report -DrepoToken=$repo_token
  - pip install --user codecov
  - codecov
